[project]
name = "advent-of-code-solutions"
version = "0.1.0"
description = "Solutions for Advent of Code"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "pandas>=2.3.3",
]
